---
# Service Account for Vault authentication
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-pki
  namespace: default
---
# ClusterRoleBinding for token review (required for Vault K8s auth)
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vault-pki-token-reviewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:auth-delegator
subjects:
- kind: ServiceAccount
  name: vault-pki
  namespace: default
